#ifndef TIME_WINDOW_WIDTH
#error "TIME_WINDOW_WIDTH should be defined before including 'time_window_widths.h'."
#endif

TIME_WINDOW_WIDTH(1m,ONE_MINUTE_IN_MS)
TIME_WINDOW_WIDTH(3m,(ONE_MINUTE_IN_MS*3))
TIME_WINDOW_WIDTH(10m,(ONE_MINUTE_IN_MS*10))
TIME_WINDOW_WIDTH(30m,(ONE_MINUTE_IN_MS*30))
TIME_WINDOW_WIDTH(1h,ONE_HOUR_IN_MS)
TIME_WINDOW_WIDTH(4h,(ONE_HOUR_IN_MS*4))
TIME_WINDOW_WIDTH(1d,ONE_DAY_IN_MS)
TIME_WINDOW_WIDTH(1w,ONE_WEEK_IN_MS)
